### ISSUE TITLE
Add `composed: true` so events propogate across Shadow DOM boundary

### ISSUE THREAD

**Issue by loganvolkers** [saasquatch/dom-context#3]
See: https://javascript.info/shadow-dom-events#event-composed

**Comment by weaintplastic** [comment]
Hey @loganvolkers. First of all, thank you so much for creating this library.

I'd be interested in having this feature as I'm trying to share a state across the boundaries of Shadow DOM. I'm happy to contribute and create a PR but first wanted to discuss this with you. We could:

a) Hardcode `composed: true` where the custom event is emitted
b) Add an option to the `ContextProvider` to enable Shadow DOM propagation. 

Option a) would be the fastest but not backward-compatible.
Option b) would be backward-compatible if the default value for `composed` is `false`

Let me know what you think and I'll prepare a PR for this.

**Comment by weaintplastic** [comment]
My bad, I just stumbled upon your pull request https://github.com/saasquatch/dom-context/pull/5

Great to see so many new features being implemented. Please let me know if I can be of any help to get this PR merged and released.

**Comment by loganvolkers** [comment]
Thanks for the reminder @weaintplastic. How are you using dom-context? Via stencil-hooks or another wrapper, or directly?

**Comment by loganvolkers** [comment]
Closed via #5 and deployed as version v1.2.0

**Comment by weaintplastic** [comment]
@loganvolkers thanks for merging and releasing so quickly. 

I'm using `dom-context` directly. I've tried stencil-hooks first but failed getting in running without errors. I've created a small more opinionated wrapper around ContextProvider and ContextListener.

I'm using dom-context to switch the mode (dark, light) of a group of components with a single `<mode-provider>` as a parent.

**Comment by loganvolkers** [comment]
Sounds like exactly what dom context is meant for, great!

If you have any bugs with stencil hooks, we're maintainers of that too.

Also if you're looking for work, saasquatch is hiring :)

**Comment by weaintplastic** [comment]
I'll give the hooks another try and let you know in case I stumble upon something odd. 

Thanks again for taking care of my request so quickly.
